=== walkie/CPP-Parser/xml/Schema3.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:complexType name="Document">
		<xsd:annotation>
			<!-- appinfo is intended for machine readable, document is form human readable -->
			<xsd:appinfo>
				Document{
				dimensions :: Dimensions
				object :: Object
				}
			</xsd:appinfo>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="dimensions" type="Dimensions" />
			<xsd:element name="object" type="Object"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="Dimensions">
		<xsd:annotation>
			<xsd:appinfo>
				Dimensions :: [Dimension]
		</xsd:appinfo>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="dimension" type="Dimension" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="Dimension">
		<xsd:annotation>
			<xsd:appinfo>
				Dimension {
				name :: String
				tags :: Tags
				default :: Tag
				}
			</xsd:appinfo>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="name" type="xsd:string"/>
			<xsd:element name="tags" type="Tags" maxOccurs="unbounded"/>
			<xsd:element name="default" type="Tag">
				</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:simpleType name="Tag">
		<xsd:annotation>
			<xsd:appinfo>
				Tag::String
			</xsd:appinfo>
		</xsd:annotation>
		<xsd:restriction base="xsd:string">
			<xsd:minLength value="1"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:complexType name="Tags">
		<xsd:annotation>
			<xsd:appinfo>
				Tags:: [Tag]
	</xsd:appinfo>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="tag" type="Tag" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="Object" abstract="true"/>
	<xsd:complexType name="Part">
		<xsd:annotation>
			<xsd:appinfo>
				Part {
				data :: "arbitrary data/blob type"
				subObjects ::
				[Object]
				}
			</xsd:appinfo>
		</xsd:annotation>
		<xsd:complexContent>
			<xsd:extension base="Object">
				<xsd:sequence>
					<xsd:element name="data"/>
					<xsd:element name="subObjects">
						<xsd:complexType>
							<xsd:sequence>
								<xsd:element name="object" minOccurs="0" maxOccurs="unbounded"/>
							</xsd:sequence>
						</xsd:complexType>
					</xsd:element>
				</xsd:sequence>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
	<xsd:element name="Object" type="Object"/>
	<xsd:complexType name="Choice">
		<xsd:annotation>
			<xsd:appinfo>
				Choice {
				alternatives :: [Alternative]
				}
		</xsd:appinfo>
		</xsd:annotation>
		<xsd:complexContent>
			<xsd:extension base="Object">
				<xsd:sequence>
					<xsd:element name="alternatives">
						<xsd:complexType>
							<xsd:sequence>
								<xsd:element name="alternative" type="Alternative" maxOccurs="unbounded"/>
							</xsd:sequence>
						</xsd:complexType>
					</xsd:element>
				</xsd:sequence>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
	<xsd:complexType name="Alternative">
		<xsd:annotation>
			<xsd:appinfo>
				Alternative {
				part :: Part
				label :: Tags
				}
			</xsd:appinfo>
		</xsd:annotation>
		<xsd:complexContent>
			<xsd:extension base="Object">
				<xsd:sequence>
					<xsd:element name="part" type="Part"/>
					<xsd:element name="label" type="Tags"/>
				</xsd:sequence>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
	<xsd:simpleType name="Name">
		<xsd:annotation>
			<xsd:appinfo>
				Name :: String
		</xsd:appinfo>
		</xsd:annotation>
		<xsd:restriction base="xsd:string">
			<xsd:minLength value="2"></xsd:minLength>	
				</xsd:restriction>
	</xsd:simpleType>
	<xsd:complexType name="Let">
		<xsd:annotation>
			<xsd:appinfo>
				Let {
				binding :: Binding
				body :: Object
				}
		</xsd:appinfo>
		</xsd:annotation>
		<xsd:complexContent>
			<xsd:extension base="Object">
				<xsd:sequence>
					<xsd:element name="binding" type="Binding"/>
					<xsd:element name="body" type="Object"/>
				</xsd:sequence>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
	<xsd:complexType name="Binding">
		<xsd:annotation>
			<xsd:appinfo>
				Binding {
				name :: Name
				value :: Object
				}
			</xsd:appinfo>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="name" type="Name"/>
			<xsd:element name="value" type="Object"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="Variable">
		<xsd:annotation>
			<xsd:appinfo>
				Variable {
				name :: Name
				}
			</xsd:appinfo>
		</xsd:annotation>
		<xsd:complexContent>
			<xsd:extension base="Object">
				<xsd:sequence>
					<xsd:element name="name" type="Name"/>
				</xsd:sequence>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
	<xsd:element name="document" type="Document"/>
</xsd:schema>

=== walkie/CPP-Parser/xml/Schema3Test.xml
<?xml version="1.0" encoding="UTF-8"?>
<document xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Schema3.xsd">
	<dimensions>
		<dimension>
			<name>Release</name>
			<tags><tag>1.4</tag><tag>5</tag></tags>
			<default>1.4</default>
		</dimension>
	</dimensions>
		<object xsi:type="Part">
			<data>blah blah</data>
			<subObjects>
			<object xsi:type="Variable">
				<name>Test</name>
			</object>
			</subObjects>
		</object>
		
</document>
