=== walkie/CPP-Parser/xml/Schema4.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:complexType name="Document">
		<xsd:annotation>
			<!-- appinfo is intended for machine readable, document is for human readable -->
			<xsd:appinfo>
				Document{
				dimensions :: Dimensions
				object :: Object
				}
			</xsd:appinfo>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="dimensions" type="Dimensions"/>
			<xsd:element ref="object" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="Dimensions">
		<xsd:annotation>
			<xsd:appinfo>
				Dimensions :: [Dimension]
		</xsd:appinfo>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="dimension" type="Dimension" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="Dimension">
		<xsd:annotation>
			<xsd:appinfo>
				Dimension {
				name :: String
				tags :: Tags
				default :: Tag
				}
			</xsd:appinfo>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="name" type="xsd:string"/>
			<xsd:element name="tags" type="Tags" maxOccurs="unbounded"/>
			<xsd:element name="default" type="Tag"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:simpleType name="Tag">
		<xsd:annotation>
			<xsd:appinfo>
				Tag::String
			</xsd:appinfo>
		</xsd:annotation>
		<xsd:restriction base="xsd:string">
			<xsd:minLength value="1"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:complexType name="Tags">
		<xsd:annotation>
			<xsd:appinfo>
				Tags:: [Tag]
	</xsd:appinfo>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="tag" type="Tag" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="Object">
		<xsd:sequence>
			<xsd:element name="data"/>
			<xsd:element ref="object"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="Choice">
		<xsd:annotation>
			<xsd:appinfo>
				Choice {
				alternatives :: [Alternative]
				}
		</xsd:appinfo>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="alternatives">
				<xsd:complexType>
					<xsd:sequence>
						<xsd:element name="alternative" type="Alternative" maxOccurs="unbounded"/>
					</xsd:sequence>
				</xsd:complexType>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="Alternative">
		<xsd:annotation>
			<xsd:appinfo>
				Alternative {
				object :: Object
				label :: Tags
				}
			</xsd:appinfo>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element ref="object"/>
			<xsd:element name="label" type="Tags"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:simpleType name="Name">
		<xsd:annotation>
			<xsd:appinfo>
				Name :: String
		</xsd:appinfo>
		</xsd:annotation>
		<xsd:restriction base="xsd:string">
			<xsd:minLength value="1"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:complexType name="Let">
		<xsd:annotation>
			<xsd:appinfo>
				Let {
				binding :: Binding
				body :: Object
				}
		</xsd:appinfo>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="binding" type="Binding"/>
			<xsd:element name="body">
				<xsd:complexType>
					<xsd:sequence>
						<xsd:element ref="object"/>
					</xsd:sequence>
				</xsd:complexType>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="Binding">
		<xsd:annotation>
			<xsd:appinfo>
				Binding {
				name :: Name
				value :: Object
				}
			</xsd:appinfo>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="name" type="Name"/>
			<xsd:element name="value">
				<xsd:complexType>
					<xsd:sequence>
						<xsd:element ref="object"/>
					</xsd:sequence>
				</xsd:complexType>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="Variable">
		<xsd:annotation>
			<xsd:appinfo>
				Variable {
				name :: Name
				}
			</xsd:appinfo>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="name" type="Name"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="Part">
		<xsd:sequence>
			<xsd:element name="data" nillable="true"/>
			<xsd:element name="subObjects" minOccurs="0">
				<xsd:complexType>
					<xsd:sequence>
						<xsd:element ref="object" maxOccurs="unbounded"/>
					</xsd:sequence>
				</xsd:complexType>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="With">
		<xsd:sequence>
			<xsd:element name="dimension" type="Dimension" minOccurs="1" />
			<xsd:element name="choose">
			 	<xsd:complexType>
					<xsd:sequence>
						<xsd:element name="binding" type="Binding" minOccurs="1" />
					</xsd:sequence>
				</xsd:complexType>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:element name="with" type="With" substitutionGroup="object" />
	<xsd:element name="variable" type="Variable" substitutionGroup="object"/>
	<xsd:element name="let" type="Let" substitutionGroup="object"/>
	<xsd:element name="choice" type="Choice" substitutionGroup="object"/>
	<xsd:element name="part" type="Part" substitutionGroup="object"/>
	<xsd:element name="object" abstract="true"/>
	<xsd:element name="document" type="Document"/>
</xsd:schema>

=== walkie/CPP-Parser/xml/webviewer/TwiceExampleWithLet.xml
<?xml version="1.0" encoding="UTF-8"?>
<document xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Schema4.xsd">
<dimensions>
	<dimension>
		<name>Variable</name>
		<tags>
			<tag>X</tag>
			<tag>Y</tag>
		</tags>
		<default>X</default>
	</dimension>
	<dimension>
		<name>Implementation</name>
		<tags>
			<tag>Plus</tag>
			<tag>Times</tag>
		</tags>
		<default>Plus</default>
	</dimension>
</dimensions>
<part>
	<data/>
	<subObjects>
		<let>
			<binding>
				<name>v</name>
				<value>
					<choice>
					<alternatives>
						<alternative><part><data>x</data></part><label><tag>X</tag></label></alternative>
						<alternative><part><data>y</data></part><label><tag>Y</tag></label></alternative>
					</alternatives>
					</choice>
				</value>
			</binding>
			<body>
				<part>
					<data>twice</data>
					<subObjects>
						<variable>v</variable>
						<part><data>=</data></part>
						<choice>
							<alternatives>
								<alternative>
									<part>
										<data/>
										<subObjects>
											<variable>v</variable>
											<part><data>+</data></part>
											<variable>v</variable>
										</subObjects>
									</part>
									<label><tag>Plus</tag></label>
								</alternative>
								<alternative>
									<part>
										<data/>
										<subObjects>
											<part><data>2*</data></part>
											<variable>v</variable>
										</subObjects>
									</part>
									<label><tag>Times</tag></label>
								</alternative>
							</alternatives>
						</choice>
					</subObjects>
				</part>
			</body>
		</let>
	</subObjects>
</part>
</document>

=== walkie/CPP-Parser/xml/webviewer/TwiceExampleBad.xml
<?xml version="1.0" encoding="UTF-8"?>
<document xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Schema4.xsd">
<dimensions>
	<dimension>
		<name>Variable</name>
		<tags>
			<tag>X</tag>
			<tag>Y</tag>
		</tags>
		<default>X</default>
	</dimension>
	<dimension>
		<name>Implementation</name>
		<tags>
			<tag>Plus</tag>
			<tag>Times</tag>
		</tags>
		<default>Plus</default>
	</dimension>
</dimensions>
<part>
	<data/>
	<subObjects>
		<part>
			<data>twice </data>
		</part>
		<choice>
			<alternatives>
				<alternative><part><data>x</data></part><label><tag>X</tag></label></alternative>
				<alternative><part><data>y</data></part><label><tag>Y</tag></label></alternative>	
			</alternatives>
		</choice>
		<part>
			<data> = </data>
		</part>
		<choice>
			<alternatives>
				<alternative>
					<choice>
						<alternatives>
							<alternative>
								<part><data>x+x</data></part>
								<label>
									<tag>Plus</tag>
								</label>
							</alternative>
							<alternative>
								<part><data>2*x</data></part>
								<label>
									<tag>Times</tag>
								</label>
							</alternative>
						</alternatives>
					</choice>
					<label>
						<tag>X</tag>
					</label>
				</alternative>
				<alternative>
					<choice>
						<alternatives>
							<alternative>
								<part><data>y+y</data></part>
								<label>
									<tag>Plus</tag>
								</label>
							</alternative>
							<alternative>
								<part><data>2*y</data></part>
								<label>
									<tag>Times</tag>
								</label>
							</alternative>
						</alternatives>
					</choice>
					<label>
						<tag>Y</tag>
					</label>
				</alternative>
			</alternatives>
		</choice>
	</subObjects>
</part>
</document>

=== walkie/CPP-Parser/xml/Schema4Test.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="Schema4Css.css"?>
<document xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Schema4.xsd">
	<dimensions>
		<dimension>
			<name>Release</name>
			<tags>
				<tag>Full</tag>
				<tag>Trial</tag>
			</tags>
			<default>Trial</default>
		</dimension>
		<dimension>
			<name>Java Version</name>
			<tags>
				<tag>1.4</tag>
				<tag>5</tag>
			</tags>
			<default>1.4</default>
		</dimension>
	</dimensions>
	<part>
		<data>class GoodApp{</data>
		<subObjects>
			<choice>
				<alternatives>
					<alternative>
						<part>
							<data>List &lt;Job&gt;</data>
						</part>
						<label>
							<tag>5.0</tag>
						</label>
					</alternative>
					<alternative>
						<part>
							<data>List</data>
						</part>
						<label>
							<tag>1.4</tag>
						</label>
					</alternative>
				</alternatives>
			</choice>
			<part>
				<data>jobs =</data>
				<subObjects>
					<choice>
						<alternatives>
							<alternative>
								<part>
									<data>new LinkedList&lt;Job&gt;</data>
								</part>
								<label>
									<tag>5.0</tag>
								</label>
							</alternative>
							<alternative>
								<part>
									<data>new LinkedList();</data>
								</part>
								<label>
									<tag>1.4</tag>
								</label>
							</alternative>
						</alternatives>
					</choice>
					<part>
						<data>void runJobs(){</data>
						<subObjects>
							<choice>
								<!-- trialCount^T, NULL^F -->
								<alternatives>
									<alternative>
										<part>
											<data>int trialCount=0;</data>
										</part>
										<label>
											<tag>Trial</tag>
										</label>
									</alternative>
									<alternative>
										<part>
											<data/>
										</part>
										<label>
											<tag>Full</tag>
										</label>
									</alternative>
								</alternatives>
							</choice>
							<let>
								<binding>
									<name>r</name>
									<value>
										<part>
											<data>=j.run</data>
										</part>
									</value>
								</binding>
								<body>
									<let>
										<binding>
											<name>i</name>
											<value>
												<choice>
													<alternatives>
														<alternative>
															<part>
																<data>break</data>
															</part>
															<label>
																<tag>Trial</tag>
															</label>
														</alternative>
														<alternative>
															<part>
																<data/>
															</part>
															<label>
																<tag>Full</tag>
															</label>
														</alternative>
													</alternatives>
												</choice>
											</value>
										</binding>
										<body>
											<choice>
												<alternatives>
													<alternative>
														<part>
															<data>for(r,i)</data>
														</part>
														<label>
															<tag>5.0</tag>
														</label>
													</alternative>
													<alternative>
														<part>
															<data>Iter,while(Job,r,i)</data>
														</part>
														<label>
															<tag>1.4</tag>
														</label>
													</alternative>
												</alternatives>
											</choice>
										</body>
									</let>
								</body>
							</let>
						</subObjects>
					</part>
				</subObjects>
			</part>
		</subObjects>
	</part>
</document>
