=== walkie/CPP-Parser/xml/XMLSpySchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--W3C Schema generated by XMLSpy v2009 (http://www.altova.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:complexType name="T_state">
		<xs:sequence>
			<xs:element ref="dim-def" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="T_ref">
		<xs:attribute name="var" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="i"/>
					<xs:enumeration value="r"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="T_md_doc" mixed="true">
		<xs:sequence>
			<xs:element ref="state"/>
			<xs:element ref="choice" maxOccurs="unbounded"/>
			<xs:element ref="let"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="T_let">
		<xs:sequence>
			<xs:element ref="def"/>
			<xs:element ref="let" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="var" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="i"/>
					<xs:enumeration value="r"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="T_dim-def">
		<xs:attribute name="sel-tag" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="1.4"/>
					<xs:enumeration value="Trial"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="id" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="Release"/>
					<xs:enumeration value="version"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="T_def" mixed="true">
		<xs:sequence>
			<xs:element ref="choice" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="T_choice" mixed="true">
		<xs:sequence>
			<xs:element ref="alt" maxOccurs="unbounded"/>
			<xs:element ref="choice" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="id" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="Release"/>
					<xs:enumeration value="version"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="T_alt" mixed="true">
		<xs:sequence>
			<xs:element ref="ref" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="tag" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="1.4"/>
					<xs:enumeration value="5"/>
					<xs:enumeration value="Full"/>
					<xs:enumeration value="Trial"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:element name="state" type="T_state"/>
	<xs:element name="ref" type="T_ref"/>
	<xs:element name="md_doc" type="T_md_doc"/>
	<xs:element name="let" type="T_let"/>
	<xs:element name="dim-def" type="T_dim-def"/>
	<xs:element name="def" type="T_def"/>
	<xs:element name="choice" type="T_choice"/>
	<xs:element name="alt" type="T_alt"/>
</xs:schema>

=== walkie/CPP-Parser/xml/Test4.xml
<?xml version="1.0" encoding="UTF-8"?>
<md_doc xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C:\Users\WEINIA~1\workspace\toscxmlschema\src\XMLSpySchema.xsd">
	<state>
		<dim-def id="version" sel-tag="1.4"/>
		<dim-def id="Release" sel-tag="Trial"/>
	</state>
	public class
	<choice id="version">
		<alt tag="1.4">List</alt>
		<alt tag="5">List&lt;Job&gt;</alt>
	</choice>
	runJob
	<choice id="Release">
		<alt tag="Trial">trialCount</alt>
		<alt tag="Full"/>
	</choice>
	<let var="r">
		<def>j.run</def>
		<let var="i">
			<def>
				<choice id="Release">
					<alt tag="Trial">break</alt>
					<alt tag="Full"/>
			for
			<choice id="version">
						<alt tag="5">
							<ref var="i"/>
						</alt>
						<alt tag="1.4">
			Iter, while &lt;Job, <ref var="r"/>
							<ref var="i"/>&gt;
			</alt>
					</choice>
				</choice>
			</def>
		</let>
	</let>
</md_doc>
